/**
 * The site gate's stored credential. Generated by scripts/set-password.mjs —
 * edit that, not this.
 *
 * This is a curtain, not a lock. The check runs in the browser after every
 * file has already been served, so the page source, the bundled JS and every
 * asset URL remain reachable without ever meeting it. These values sit in a
 * public repo; a short or numeric password is recoverable from them in under
 * a second. Never reuse a password that protects anything else.
 */
export const GATE_SALT = "bc91a4219183f22e872b0f133fec08d8";
export const GATE_HASH = "b8df9f8d299d40e9d3ddd6320531682df73ac329561da00b32c579a6e321258d";

/** localStorage key holding the unlocked flag, per browser. */
export const GATE_KEY = "aj-gate";
